version: '3.7'

networks:
  localdev:
    name: localdev

services:
  project-api:
    container_name: 'project-api'
    build: './server'
    ports:
      - "7000:80"
    networks:
      - localdev
    image: project-api-image:latest