name: Publish to Azure

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - ci-cd-pipeline
  
env:
  AZURE_WEBAPP_NAME: teamprojectapi2023
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '7.0'       

jobs:
  publish: 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 

    - name: dotnet build and publish
      run: |
        dotnet restore server/
        dotnet build server/ --configuration Release
        dotnet publish server/ -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/drop' 

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/drop'
